SUBROUTINE INPUTET ()
! THE SUBROUTINE IS USED TO READ THE "ET.INP" FILE
! DATA CONTAINED IN THE FILE INCLUDE:
! 1 -- TIDAL PARAMETERS


  USE M_TIDE
  IMPLICIT NONE
  INTEGER(4) :: fET
  INTEGER(4) :: NLSKIP
  INTEGER(4):: ios
  
 
  fET=1221
  OPEN(UNIT=fET,FILE='ET.INP',STATUS='OLD')
  
  CALL SKPCOM (fET, NLSKIP)
  READ (fET,*,iostat=ios) MSL, TAMP, TPESEC, PBCRHO, PBCTEMP, PBCSAL
  if(ios/=0) call ErrorIO('Error reading tide parameters')

RETURN

END SUBROUTINE